---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-un
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/first-volume"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-deux
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/second-volume"
